# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e7c85577210f69aa6e238d065af43b5d74db242371f56a6d8ea8fbeff31eca2e07952a79d4cad4ca82a119d0eb5359917df8733de70cc139ff5a2d1999259ca

test:
  secret_key_base: 2bcb975cfbb59452df821b26f13fc15545ed7453063afaaa9de5f82c917c75de36a5f8489a639dd8272ecc58f232a2c4a2bb7e2cee871432cf4fc36dcd9ea65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
